development:
  dialect: postgres
  database: hotel-reservation_development
  user: hotel_user
  password: hotel_pass
  host: localhost 
  pool: 5
  port: 5432

production:
  url: {{envOr "DB_URL" "postgres://user:pass@host:port/database?"}}

