development:
  dialect: postgres
  database: database
  user: user
  password: pass
  host: host
  pool: 5
  port: port

production:
  url: {{envOr "DB_URL" "postgres://user:pass@host:port/database?"}}

