name: feature build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'infrastructure/**'
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Docker compose + healthchecks
        run: |
          docker-compose up -d

       
